### ISSUE TITLE
Cannot remove an observer for the key path "layer.sublayers" from <_UIAlertControllerShimPresenterWindow 0x102cdacd0> because it is not registered as an observer.

### ISSUE THREAD

**Issue by kross50** [dbukowski/DBDebugToolkit#10] opened 2017-05-19 03:34 UTC
- (void)windowDidResignKey:(UIWindow *)window {
    [window removeObserver:self forKeyPath:@"layer.sublayers"]; // causes exception if UIPickerView is displayed from modal form
}

*** Terminating app due to uncaught exception 'NSRangeException', reason: 'Cannot remove an observer <DBPerformanceToolkit 0x1741193e0> for the key path "layer.sublayers" from <_UIAlertControllerShimPresenterWindow 0x102cdacd0> because it is not registered as an observer.'

Also wrapping a try-catch around it does not fix the issue.

**Comment by dbukowski** [comment] 2017-05-28 21:58
Hello @kross50!
Thank you for reporting this issue and sorry for responding so late. Could you please provide some more details? How exactly do you display the `UIPickerView`? I am asking because I failed to reproduce that issue.

**Comment by vphamdev** [comment] 2018-01-05 23:40
@dbukowski we experienced this one too, and found it to happen only on iOS 10 and not 9 or 11. The view does not need to be displayed, we crash after did finish launching because the window cannot unregister.

**Comment by dbukowski** [comment] 2018-04-11 09:30
This should be fixed in the new version - v. 0.3.1.
If this problem occurs again, please use crash reports included in the library to provide more details.

**Closed by dbukowski** 2018-04-11 09:30 UTC
