### ISSUE TITLE
DBDebugToolkit crashing due to nil object being inserted in Array

### ISSUE THREAD

**Issue by shoaibsadanaut** [dbukowski/DBDebugToolkit#59] opened 2022-02-09 11:06 UTC
**Crash message**
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSArrayM insertObject:atIndex:]: object cannot be nil'

**Stack trace**
<img width="1552" alt="Screenshot 2022-02-09 at 4 03 50 PM" src="https://user-images.githubusercontent.com/73075608/153186136-9042959c-7dc4-487c-8647-8d776fea4cc3.png">

**Comment by gamada-de** [comment] 2022-02-09 15:45
thx for your hint. This crash is a duplicate of the issue https://github.com/dbukowski/DBDebugToolkit/issues/56

**Closed by gamada-de** 2022-02-09 15:45 UTC

**Comment by gamada-de** [comment] 2022-02-09 16:06
@shoaibsadanaut i hope this is now fixed with version [0.8.0](https://github.com/dbukowski/DBDebugToolkit/releases/tag/0.8.0)

**Comment by shoaibsadanaut** [comment] 2022-02-10 05:01
I can confirm this is fixed now.
